[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

# Include the public directory in the build output
[[build.processing.included_files]]
  path = "public/messages/**"

# Copy the public directory to the publish directory
[[build.processing.copy]]
  from = "public"
  to = "public"

# Configure the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
# Build environment settings
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"
  YARN_PRODUCTION = "false"
  CI = "false"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/messages/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Access-Control-Allow-Origin = "*"
