[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

# Include all necessary files in the build
[[build.include]]
  # Include the entire public directory
  from = "public"
  to = "/"
  status = 200

# Ensure the messages directory is included at the root
[[build.include]]
  from = "public/messages"
  to = "/messages"
  status = 200
  force = true

# Include individual JSON files in the messages directory
[[build.include]]
  from = "public/messages/*.json"
  to = "/messages/"
  status = 200
  force = true

# Include the .next/static directory for static assets
[[build.include]]
  from = ".next/static"
  to = "/_next/static"
  status = 200
  force = true

# Configure the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
# Build environment settings
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"
  YARN_PRODUCTION = "false"
  CI = "false"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/messages/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Access-Control-Allow-Origin = "*"
